### ISSUE TITLE
Dumping private key in identity certificates

### ISSUE THREAD

**Issue by holiman** [ptoomey3/Keychain-Dumper#13]
The tool seems to work great, I was able to dump keychain on a iphone 5S / 7.1.2. However, when dumping identities, the actual private key does not seem to be dumped. 

Example: 

```
Key

---
Entitlement Group: com.apple.apsd
Label: APSClientIdentity
Application Label: <20byte identifier>
Key Class: Private
Permanent Key: True
Key Size: 1024
Effective Key Size: 1024
For Encryption: False
For Decryption: True
For Key Derivation: True
For Signatures: True
For Signature Verification: False
For Key Wrapping: False
For Key Unwrapping: True
```

Is it possible to extract the actual 128byte private key DATA also, or am I missing something?

**Comment by reinitialized** [comment]
See https://github.com/reinitialized/Keychain-Dumper/commit/4c558843e00516513c8cee7b47fe0605a883e180

**Comment by angelovAlex** [comment]
@reinitialized Can you upload a new signed binary?

**Comment by louis-web** [comment]
@rjoudrey 
`
See reinitialized/Keychain-Dumper@4c55884
`
Can not open now.

**Comment by rjoudrey** [comment]
I fixed the link

**Comment by louis-web** [comment]
thanks for fixed it.
I found a new question: Can not dump ECPrivateKey.

**Comment by ptoomey3** [comment]
Closing as stale.
