### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by xu-xiang** [ptoomey3/Keychain-Dumper#19]
./keychain_dumper

No Generic Password Keychain items found.
No Internet Password Keychain items found.

**Comment by JPaulMora** [comment]
Your phone might be locked, unlock and try again: Success!

**Comment by ThePantsThief** [comment]
I'm also having this issue. My phone is unlocked.

**Comment by wengxianxun** [comment]
so am i, how to do it?

**Comment by Daemonceltics** [comment]
./keychain_dumper -a  is ok for me (iOS 10.2 iPhone 5s)

**Comment by ptoomey3** [comment]
Closing as stale.
