### ISSUE TITLE
May i use keychain_dumper for OS X?

### ISSUE THREAD

**Issue by ultralKDes** [ptoomey3/Keychain-Dumper#20]
Can i use keychain_dumper for keychain-2.db on OS X.
Thanks so much

**Comment by ptoomey3** [comment]
Ice never tried building/running on OS X. But, my guess is that the code would have to be updated to account for the differences between keychains on the two platforms.

**Comment by ultralKDes** [comment]
Hope to see it soon. Thank you so much.
