### ISSUE TITLE
Showing app encrypted data from KeyChain

### ISSUE THREAD

**Issue by rustymagnet3000** [ptoomey3/Keychain-Dumper#24]
@ptoomey3 thank you so much for KeyChain dumper.  I love this tool.

Are there any hidden options for displaying the raw data of the KeyChain Data field?     I cannot see ciphertext value when I run a dump.  The field always appears as (null).  I attached an example below.

It is an iOS app. The app performs an AES256 encrypt function before storing data within KeyChain.  It looks like the Ciphertext is encoded using NSUTF8StringEncoding before persisting in KeyChain.
## Generic Password

Service: com.monkey.zoo
Account: fYEzNKo3h0KXfgs2BmNy
Entitlement Group: FEY6Z943BR.*
Label: (null)
Generic Field: fYEzNKo3h0KXfgs2BmNy
Keychain Data: (null)

**Comment by ptoomey3** [comment]
Closing as stale.
