### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by jjacquet** [ptoomey3/Keychain-Dumper#26]
MacBook-Air.local 15.6.0 Darwin Kernel Version 15.6.0: root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

i386

**Comment by ptoomey3** [comment]
Are you trying to run this on your computer/emulator? This only works on ARM based iOS devices.

**Comment by jjacquet** [comment]
I am trying to remove a keychain on a device from the terminal for automation purposes

**Comment by ptoomey3** [comment]
Are you trying to run this from the Mac terminal or from the jailbroken iPhone's terminal? This app can only be run from a jailbroken iPhone that it has been copied to.

**Comment by Daemonceltics** [comment]
The keychain_dumper only run in arm arch ,your Mac CPU is x86 arch ,so.

**Comment by ptoomey3** [comment]
Assuming the original submitter was running in the emulator (which has never worked).

**Comment by iddoeldor** [comment]
happens to me also 

`Darwin iPhone 17.3.0 Darwin Kernel Version 17.3.0: Mon Nov  6 21:19:15 PST 2017; root:xnu-4570.32.1~1/RELEASE_ARM64_S8000 iPhone8,2 arm64 N66AP Darwin`
