### ISSUE TITLE
iOS 11.3+ : Access an item with TouchID/FaceID

### ISSUE THREAD

**Issue by priyankn** [ptoomey3/Keychain-Dumper#32]
Hi, 

Can keychain items be accessed normally via this tool when the following SecAccessControlCreateFlags are set?

https://developer.apple.com/documentation/security/secaccesscontrolcreateflags

I tested it quickly and the answer is no (well, except for .userPresence, where a passcode is required), but want to be 100% sure if my test app was behaving correctly.

**Comment by ismyhc** [comment]
@priyankn Im interested in this too. Are you saying that you can or cannot see decrypted data when the .usePresence flag was use to store value?

**Comment by priyankn** [comment]
@ismyhc Yes, I can see the data, because it constrains to access an item with either biometry **OR** passcode.

Nevertheless, I found the objection framework to work better in this case - FYI to all future ppl 
https://github.com/sensepost/objection

**Comment by ptoomey3** [comment]
Closing as stale.
