### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by alukanin** [ptoomey3/Keychain-Dumper#4]
Can't run the program for some reason. It's killed right away with the message "Killed: 9" (no matter whether it's with the arg "-e" or not).

Access rights - 777, trying to run from /tmp. I've tried to compile it myself as well the binary attached.

**Comment by novitae** [comment]
moving the file to `/bin` worked for me. I was in `/tmp`, where it seems the authorizations to run executables are not the same than in `/bin`.
