### ISSUE TITLE
Remove binaries from repository

### ISSUE THREAD

**Issue by Jnchi** [ptoomey3/Keychain-Dumper#45]
Revert https://github.com/ptoomey3/Keychain-Dumper/commit/e35a0a6bcab213a2ce0b9628300d3cde1038f7c7.

If they need a pre-built binary, create a pre-release and upload it there instead.

Resources:

- https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git

**Comment by alyxferrari** [comment]
@ptoomey3 please do this.

**Comment by ptoomey3** [comment]
This repo goes back a few years...I agree I wouldn't follow this pattern here in 2020. I'll take a look at uploading a release and deleting the binary later this week.

**Comment by ptoomey3** [comment]
Removed binaries from the repo and cut a release in https://github.com/ptoomey3/Keychain-Dumper/releases/tag/1.0.0.
