### ISSUE TITLE
Can this tool export the private key of the [Apple Iphone Device CA] certificate?

### ISSUE THREAD

**Issue by hleungg** [ptoomey3/Keychain-Dumper#47]
Can this tool export the private key of the [Apple Iphone Device CA] certificate? thanks.

**Comment by ptoomey3** [comment]
Is that some apple specific thing or is it some MDM thing? If it is stored in the keychain it should be exportable.

**Comment by hleungg** [comment]
The certificate is requested to be signed to albert.apple.com when the IOS is activating. I am not sure this crt and private-key is stored in the keychain.

**Comment by hleungg** [comment]
The PUSH certificate is generated when the device is registered and activated at Apple. During the 1st connection to Apple's server, a certificate request is sent to albert.apple.com. This server runs a certificate authority, called Apple Iphone Device CA, in charge of signing every request.

This certificate is very sensitive as it is the one in charge of ALL PUSH communications from the device

**Comment by nicolas17** [comment]
The private key of the CA is not on the device, it's on Apple's servers, so no tool running on the device could possibly extract it.

**Comment by ptoomey3** [comment]
Thanks for the reply. Closing this out since I think the answer is "no".
