### ISSUE TITLE
seems not working at ios13

### ISSUE THREAD

**Issue by youngzzzzzzz** [ptoomey3/Keychain-Dumper#56]
iphone7 ios13.5.1 checkra1n

showing this:

[INFO] No Generic Password Keychain items found.
[HINT] You should unlock your device!
[INFO] No Internet Password Keychain items found.
[HINT] You should unlock your device!
[INFO] No Identity Keychain items found.
[HINT] You should unlock your device!
[INFO] No Certificate Keychain items found.
[HINT] You should unlock your device!
[INFO] No Key Keychain items found.
[HINT] You should unlock your device!

**Comment by youngzzzzzzz** [comment]
my bad

**Comment by ihbing** [comment]
I have the same problem, how did you solve it?
