### ISSUE TITLE
iOS 13.5.1 - Keychain data not decrypted

### ISSUE THREAD

**Issue by p4ever** [ptoomey3/Keychain-Dumper#62]
With iOS 13.5.1, after updating the entitlements for each element we found in the keychain, we get the data still encrypted like so:

```
Internet Password
-----------------
Server: Manatee
Account: FD4F3030-750B-4DBE-B319-5F5A33A6088A
Entitlement Group: com.apple.security.ckks
Label: (null)
Accessible Attribute: kSecAttrAccessibleWhenUnlocked, protection level 2 (default)
Keychain Data: UY4cJvCwK1u/s7aXIRIZx7fB7XwXstFcxxxxxxxxxxxxxxxxLjKuz74kgSd3uqcgUPr/onJ7//uzA3B2FYiw==

Internet Password
-----------------
Server: Manatee
Account: 0D28927E-4722-4852-8D5C-0A64719A35DB
Entitlement Group: com.apple.security.ckks
Label: (null)
Accessible Attribute: kSecAttrAccessibleAfterFirstUnlock, protection level 1
Keychain Data: PJPkpXO1tlZEhU8VaMdyLTUAspjYpGk/CxxxxxxxxxxG8GfA/lVwF2gi3hKNo9lkQPl+X2rSb8w==
```

I've replaced some of the data with 'x' just to be extra safe exposing this informations

**Comment by bensh** [comment]
I would guess that this is because the data is encrypted before being stored in the keychain. 
I see the same running it on iOS 12.4.3 and 11.2.5

this tool is a dumper, not a decrypter.

**Comment by ptoomey3** [comment]
If that is the case I'll close this out and folks can re-open if still relevant.
