### ISSUE TITLE
Error with Compiling the Keychain Dumper

### ISSUE THREAD

**Issue by m1kedaws0n** [ptoomey3/Keychain-Dumper#7]
I'm currently on an iPhone 4 with iOS 5.0.1

After executing the 'make' command I get the following: 

/Users/Mike/Desktop/Key_Dump/toolchain/usr/bin/gcc -Os -Wimplicit -isysroot /Users/Mike/Desktop/Key_Dump/sdk -arch armv6 -c main.m
make: /Users/Mike/Desktop/Key_Dump/toolchain/usr/bin/gcc: No such file or directory
make: *** [main.o] Error 1

any idea why?

**Comment by philross88** [comment]
I ran the gcc command manually and i am getting following error message
#gcc -Os -Wimplicit -isysroot /User/phil/Desktop/Keychain-Dumper/sdk -arch armv6 -c main.m
main.m:318:2: error: selector element type 'id *' is not a valid object
        for (id *kSecClassType in (NSArray *) arguments) {
        ^    ~~~~~~~~~~~~~~~~~~~~
1 error generated.
