### ISSUE TITLE
ios 15 - ldid missing Info.plist

### ISSUE THREAD

**Issue by bensh** [ptoomey3/Keychain-Dumper#73]
Just fiddling around with keychain_dumper on iOS15.6 jailbroken with palera1n and went to sign the binary with ldid with a modified ent.xml file and getting the following:

```
iPhone# ldid -S/private/var/root/keychain_ent.xml /var/jb/usr/sbin
ldid: Could not find Info.plist
```

No idea what this is or means, works fine on iOS 14.4. 

EDIt: Sorry!! my mistake! it works when adding the binary actually in the path haha. mind exploding since jailbreaking palera1n and having to find all testing tools again.

**Comment by ptoomey3** [comment]
I'm a bit confused by the output above since it looks like the second argument to `ldid` is a directory (`/var/jb/usr/sbin`).  Are you using the shell script to do this: https://github.com/ptoomey3/Keychain-Dumper/blob/master/updateEntitlements.sh ?

**Comment by bensh** [comment]
error behind keyboard! works fine

```
iPhone:~ root# ldid -S/private/var/root/keychain_ent.xml /var/jb/usr/sbin/keychain_dumper
iPhone:~ root# keychain_dumper -a | head
Generic Password
----------------
Service: com.apple.gs.beta.auth.com.apple.account.AppleIDAuthentication.token
```

**Comment by ptoomey3** [comment]
😅 - Glad it was an easy "fix".
