### ISSUE TITLE
Killed: 9 on iOS 5.1.1

### ISSUE THREAD

**Issue by coverxit** [ptoomey3/Keychain-Dumper#8]
I just upload "keychain_dumper"  via SSH to my iPad 2(it's iPad 2,1) which is running iOS 5.1.1.
But once I try to run ./keychain_dumper,
It said that "Killed: 9"
Then I tried "ldid -S keychain_dumper" and then "./keychain_dumper", I still received a "Killed: 9".
I don't have a Mac, so it could be a diffcult thing for me to compile it by myself.
So If there is anyway to solve this problem?

**Comment by ymsying** [comment]
you can run the rest of commands to dump the keychain entries
`ldid -S keychain_dumper`

**Comment by jachu1611** [comment]
i have the same issue with iOS version 12.1.1 What will i do ?
i tried ldid and all those stuffs but still its not working.

**Comment by ptoomey3** [comment]
Has anyone here tried recompiling to know if that addresses the issue? I've fallen out of the jailbreak world, so don't have easy access to a device to test on.

**Comment by coverxit** [comment]
@ptoomey3 Thanks for your response that I’ve been waiting for 6 years 🤣. However, I’m out of jailbreak world too.

**Comment by FQuen** [comment]
I'm also running iOS 12.1.1 (unc0ver jailbreak) on an iphone 5S. I recompiled keychain_dumper on my mac with a self-signed certificate and I'm still getting a "killed 9".

**Comment by jachu1611** [comment]
@FQuen  refer this link https://github.com/pwn20wndstuff/Undecimus/issues/531 
My issue got solved

**Comment by yonglefu** [comment]
fixed by 
ldid -S/usr/share/entitlements/debugserver.xml keychain_dumper

**Comment by ptoomey3** [comment]
Closing a stale.
